
TOOLCHAIN_PATH = 

CC    = $(TOOLCHAIN_PATH)gcc
CPP   = $(TOOLCHAIN_PATH)g++
AS    = $(TOOLCHAIN_PATH)as
LD    = $(TOOLCHAIN_PATH)ld
AR    = $(TOOLCHAIN_PATH)ar
STRIP = $(TOOLCHAIN_PATH)strip



MODULE     := zas

